language: cpp

compiler:
  - clang
  - gcc

notifications:
  email: false

before_install:
  - wget https://github.com/google/protobuf/releases/download/v2.5.0/protobuf-2.5.0.tar.gz
  - tar -xvzf protobuf-2.5.0.tar.gz
  - cd protobuf-2.5.0
  - ./configure && sudo make install
  - cd ..
  - git clone git@github.com:gflags/gflags.git
  - cd gflags
  - mkdir build && cd build
  - cmake ..
  - make install
  - cd ../..

script:
  - mkdir build && cd build
  - make
