language: cpp

compiler:
  - gcc

notifications:
  email: false

before_install:
  - wget https://github.com/google/protobuf/releases/download/v2.5.0/protobuf-2.5.0.tar.gz
  - tar -xvzf protobuf-2.5.0.tar.gz
  - cd protobuf-2.5.0
  - ./configure && sudo make install
  - cd ..
  - ./scripts/update_cmake.sh
  - wget https://gflags.googlecode.com/files/libgflags0_2.0-1_amd64.deb
  - sudo dpkg -i libgflags0_2.0-1_amd64.deb
  - wget https://gflags.googlecode.com/files/libgflags-dev_2.0-1_amd64.deb
  - sudo dpkg -i libgflags-dev_2.0-1_amd64.deb

script:
  - mkdir build && cd build
  - make
