language: cpp

compiler:
  - gcc

notifications:
  email: false

before_install:
  - ./scripts/update_cmake.sh
  - git clone git@github.com:gflags/gflags.git
  - cd gflags
  - git reset --hard d4e971c10b1557292b5371807a23921d15e7fece
  - mkdir build && cd build
  - cmake ..
  - sudo make install

script:
  - mkdir build && cd build
  - cmake ..
  - make
