language: cpp

compiler:
  - gcc

notifications:
  email: false

before_install:
  - wget https://github.com/google/protobuf/releases/download/v2.5.0/protobuf-2.5.0.tar.gz
  - tar -xvzf protobuf-2.5.0.tar.gz
  - cd protobuf-2.5.0
  - ./configure && sudo make install
  - cd ..
  - ./scripts/update_cmake.sh
  - sudo apt-get install libgflags-dev

script:
  - mkdir build && cd build
  - make
